---
title: drawiin دراوين
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: base
  values:
    layout: base
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: base
permalink: pretty
logo: "/uploads/logo_icon.png"
description: Drawiin دراوين is a recently founded artist-run space in Carthage Mohamed Ali focused on agroecology, print, publishing, public programming and film.
description_derja: سيد دو إيوسمود تيمبور إنكيديدونت أوت لابور إت دولور ماجنا أليكوا. إكسيبتيور سينت أوككيكات كوبيداتات نون برويدنت، سونت إن كولبا كوي أوفيسيا ديسيرونت.
accent_color: "#FF7477"